name: app
dependencies:
  - python=3.8
  - psycopg2
  - pip
  - pip:
      - Django==3.1.2
      - djangorestframework==3.11.1
      - djangorestframework-simplejwt==4.4.0
      - gunicorn
      - flake8
      - django-cors-headers
      - django-extensions==2.2.5
      - Pillow