# Generated by Django 3.1.2 on 2020-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
