# Generated by Django 3.1.2 on 2020-11-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
