# Generated by Django 3.1.2 on 2020-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_seats',
            field=models.IntegerField(default=20),
        ),
    ]
