# Generated by Django 3.1.2 on 2020-11-04 17:15

from django.db import migrations, models
import workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_max_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='banner',
            field=models.ImageField(blank=True, upload_to=workshops.models.user_directory_path),
        ),
    ]
