# Generated by Django 3.1.2 on 2020-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
