# Generated by Django 3.1.2 on 2020-11-07 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0005_auto_20201106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='m2m_workshops', to=settings.AUTH_USER_MODEL),
        ),
    ]
