# Generated by Django 3.1.2 on 2020-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_auto_20201107_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('work', 'Work'), ('rela', 'Relations')], max_length=9),
        ),
    ]
